#! /bin/sh

sxhkd &

bspc monitor DP-0 -d I II III IV
bspc monitor DVI-D-0 -d V VI VII
bspc monitor DP-3 -d VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config normal_border_color "#282a36"
bspc config focused_border_color "#ff79c6"
bspc config presel_border_color "#44475a"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
